import Head from 'next/head';
import JobsContainer from '../components/JobsContainer';
import jobData from '../lib/data.json';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dev Jobs Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Dev Jobs Board</h1>
        <JobsContainer jobs={jobData} />
      </main>

      <footer></footer>
    </div>
  );
}
