import Head from 'next/head';
import JobsContainer from '../components/JobsContainer';
import JobFilterForm from '../components/JobFilterForm';
import jobData from '../lib/data.json';
import { useState } from 'react';
import MobileFormModal from '../components/MobileFormModal';

export default function Home() {
  const [formData, setFormData] = useState<{
    data: string;
    location: string;
    fullTimeOnly: boolean;
  }>({
    data: '',
    location: '',
    fullTimeOnly: false,
  });
  const [modalOpen, setModalOpen] = useState<boolean>(false);
  const toggleModal = () => {
    modalOpen ? setModalOpen(false) : setModalOpen(true);
    console.log(modalOpen);
  };
  return (
    <div className="relative">
      {modalOpen && (
        <MobileFormModal
          toggleModal={toggleModal}
          setFormData={setFormData}
          formData={formData}
        />
      )}
      <Head>
        <title>Dev Jobs Board</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-6 md:px-9 lg:px-40 xl:px-80">
        <JobFilterForm setFormData={setFormData} toggleModal={toggleModal} />
        <JobsContainer jobs={jobData} formData={formData} />
      </main>
    </div>
  );
}
